version: '3.7'

services:
  app_devway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Seoul
    networks:
      - devway_network

networks:
  devway_network:
    external: true